version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
